#!/bin/sh
TARGET=$1
TARNAME=$(basename ${TARGET})
git submodule update;
git archive -o ${TARGET} HEAD
cp etc/knomod_version BASE_VERSION
u8_gitversion etc/knomod_version > VERSION
u8_gitversion etc/knomod_version -full > FULL_VERSION
u8_gitbranch > BRANCH
tar -rf ${TARGET} VERSION BASE_VERSION FULL_VERSION BRANCH
("cd" mongo-c-driver;
 git describe > VERSION_CURRENT
 git archive --prefix=mongo-c-driver/ -o ../driver.tar HEAD);
tar -rf driver.tar mongo-c-driver/VERSION_CURRENT
tar --concatenate --file=${TARGET} driver.tar
rm driver.tar
